sudo: required

language: ruby
cache: bundler

services:
  - docker

script:
  - bundle exec rake build

deploy:
  provider: script
  script: rvm use $TRAVIS_RUBY_VERSION do bundle exec rake push
  on:
    branch: master
  skip_cleanup: true
